name: Build Extension
description: Shared Extension Build
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4

  - name: Setup Node.js
    uses: actions/setup-node@v4

  - name: Install Node Deps
    run: npm i
    shell: bash

  - name: Build
    run: npm run build-all
    shell: bash
