name: Publish Preview
on:
  push:
    branches:
    - preview
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build-extension

    - name: VSCE Publish Preview
      run: npx vsce publish --pre-release -p ${{ secrets.MARKETPLACE_TOKEN }}
