name: Publish Extension
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Install Wasm-Pack
      run: npm install -g wasm-pack

    - name: Install Node Deps
      run: npm i

    - name: Build Extension
      run: npm run build-all

    - name: Install VSCE
      run: npm install -g vsce

    - name: VSCE Login
      run: vsce login ${{ secrets.MARKETPLACE_TOKEN }}

    - name: VSCE Publish
      run: vsce package
