name: Publish Release
on:
  push:
    branches:
    - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build-extension

    - name: VSCE Publish Release
      run: vsce publish -p ${{ secrets.MARKETPLACE_TOKEN }}
