name: Publish
on:
  push:
    branches:
    - main
    - preview

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'

    - name: Install Node Deps
      run: npm i

    - name: Build
      run: npm run build-all

    - name: VSCE Package Release
      run: npx vsce package
      if: github.ref == 'refs/heads/main'

    - name: VSCE Package Preview
      run: npm version prerelease --preid preview && npx vsce package --pre-release
      if: github.ref != 'refs/heads/main'

    - name: Upload Extension Artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-vsix
        path: "*.vsix"

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Install VSCE
      run: npm i -g @vscode/vsce

    - name: Download Extension Artifact
      uses: actions/download-artifact@v4
      with:
        name: extension-vsix

    - name: VSCE Publish Release
      run: npx vsce publish --packagePath *.vsix -p ${{ secrets.MARKETPLACE_TOKEN }}
      if: github.ref == 'refs/heads/main'

    - name: VSCE Publish Preview
      run: npx vsce publish --packagePath *.vsix --pre-release -p ${{ secrets.MARKETPLACE_TOKEN }}
      if: github.ref == 'refs/heads/preview'
